config/routes.rb
Rails.application.routes.draw do
  resources :cards
  post "cards/:id"    => "cards#clone"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  mount_uploader :card_img, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy, :clone]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: '卡片已成功加入牌組！' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  # CLONE /cards/1
  # CLONE /cards/1.json
  def clone
    card = Card.find(params[:id])
    new_card=card.dup
    new_card.save

    respond_to do |format|
      format.html { redirect_to cards_url }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:card_id, :card_name, :card_desc, :card_img ,:cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(card) do |f| %>
  <% if card.errors.any? %>
      <div id="error_explanation" class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form">
  <div class="form-group" >
    <!--修改為用下拉的方式，並自動帶入名稱支付點數,說明,卡片圖片-->
    <%= f.label :卡片號碼, class:"control-label" %>

    <%= f.text_field :card_id ,class:"form-control",placeholder:"請輸入卡片號碼"%>
<!--
    <%= f.select :card_id, ['1-001','2-001'],class:"dropdown-menu"%>
-->
  </div>

  <div class="form-group">
    <%= f.label :卡片名稱, class:"control-label"  %>
    <%= f.text_field :card_name ,class:"form-control",placeholder:"請輸入卡片名稱"%>
  </div>
  <div class="form-group">
    <%= f.label :支付點數, class:"control-label"  %>
    <%= f.text_field :cost ,class:"form-control",placeholder:"請輸入卡片消耗數"%>
  </div>

  <div class="form-group">
    <%= f.label :卡片說明, class:"control-label"  %>
    <%= f.text_area :card_desc ,class:"form-control", placeholder:"請輸入卡片敘述"%>
  </div>

  <div class="from-group" style="padding-bottom:20px">
    <label>選擇卡片圖片</label>
    <%= f.file_field :card_img %>
  <!--預覽圖的呈現-->
  </div>

    <div class="from-group" style="padding-bottom:20px">
    <%= image_tag card.card_img %>
  </div>

  <div class="from-group">
  <div class="actions">
    <%= f.submit "完成",:class => 'btn btn-default' %>
    <%= link_to '回上一頁', cards_path ,:class => 'btn btn-default' %>

  </div>
  </div>

</div>
<% end %>

app/views/cards/edit.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
</nav>
<div class="container">

<%= render 'form', card: @card %>
</div>

app/views/cards/index.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">

  <div class="col-md-4">.
  </div>
  <div class="col-md-4">
    <%= image_tag("Logo.png") %>
  </div-->
  <!--div class="col-md-6">
    <%= image_tag("web_head_6v2.png") %>
  </div-->
  <div class="col-md-4">.
  </div>
  </div>
</nav>
<div class="container">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">牌組產生工具 Deck Maker ver 1.0</a>
    </div>



    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li>  <a href="#">牌組卡片總數 <span class="badge"><%= @cards.count %></span></a></li>
        <li> <%= link_to("讀取既有牌組",'#' ) %></li>
        <li> <%= link_to("儲存", '#') %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--
<table class="table">
  <thead>
    <tr>
      <th>Card</th>
      <th>Card name</th>
      <th>Card desc</th>
      <th>Card img</th>
      <th colspan="3"></th>
    </tr>
  </thead>
-->
<div class="container-fluid">
<div class="row">
    <% @cards.order("cost asc").order("card_img asc").each do |card| %>


<div class="col-sm-2" style="margin-bottom:5pt">
          <!--
        <a><%= card.card_id %></a>
      -->
      <div class="well well-sm" style="margin-bottom:4pt">
        <small><%= card.card_id %> <%= card.card_name %></small>
      </div>
<!--
        <a><%= card.card_desc %></a>
          -->
      <div>
        <%= image_tag card.card_img, class:"img-responsive"%>
      </div>
<!--
        <%= link_to 'Show', card,class:'btn btn-default' %>
-->
<div style="margin-top:5pt;margin-bottom:12pt">
<%= link_to card, method: :delete , data: { confirm: 'Are you sure?' } do%>
<button class="btn btn-danger btn-xs">
<span class='glyphicon glyphicon-minus'></span>
</button>
<%end%>
<%= link_to card, method: :clone do%>
<button class="btn btn-success btn-xs">
<span class='glyphicon glyphicon-plus'></span>
</button>
<%end%>

<%= link_to card do%>
<button class="btn btn-info btn-xs">
<span class='glyphicon glyphicon-eye-open'></span>
</button>
</div>
<%end%>



</div>
        <% end %>

    </div>

</div>

<br>
<!--改為互動式 -->




<%= link_to 'New Card', new_card_path,class:'btn btn-default' %>
</div>
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2017 Rails101s
    <br>Design by <a href="http://sdlong.logdown.com" target=_new>Tugou</a>
  </p>
</footer>

app/views/cards/new.html.erb
<div class="container">
  <nav class="navbar navbar-static-top" role="navigation">
  </nav>
<%= render 'form', card: @card%>
</div>

app/views/cards/show.html.erb
<div class="container">
  <nav class="navbar navbar-static-top" role="navigation">
  </nav>
<!--div class="alert alert-success" role="aler">
<p id="notice"><%= notice %></p>
</div-->

<div class="row">
  <div class="col-md-4">
<table class="table" style="text-align:left">
<tr>
  <td rowspan="4" style="text-align:right;border: 1px solid #ddd;">
      <%= image_tag @card.card_img.to_s %>
  </td>
  <td height="10%">
  <strong>卡片編號</strong>
  </td>
  <td height="10%" >
  <%= @card.card_id %>
  </td>
</tr>
<tr>
  <td height="10%">
  <strong>卡片名稱</strong>
</td>
<td height="10%">
  <%= @card.card_name %>
</td>
</tr>
<tr>
  <td height="10%">
  <strong>支付點數</strong>
</td>
<td height="10%">
  <%= @card.cost%>
</td>
</tr>
<tr>
<td height="70%">
<strong>卡片說明</strong>
</td>
<td height="70%">
  <%= @card.card_desc %>
</td>
</tr>
</table>
</div>
</div>

<%= link_to 'Edit', edit_card_path(@card),:class => 'btn btn-default' %>
<%= link_to 'Back', cards_path,:class => 'btn btn-default' %>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>